### ISSUE TITLE
Knowledge Clustering and \AP

### ISSUE THREAD

**Issue by nicolas-waldburger** [remimorvan/knowledge-clustering#16]
Could knowledge clustering also help by adding \AP whenever forgotten by the user?

**Comment by remimorvan** [comment]
The suggestion was partially implemented in v0.5.0 in the `anchor` feature: for now it simply prints the line number where it found a missing anchor point.
It might be enhanced later, but I am not sure 1) what a good policy would be on where to add anchor points, and 2) if automation is really necessary since the number of missing anchor points should be relatively small.

**Comment by remimorvan** [comment]
I'm closing the issue: I find the actual feature very easy to use, even on large documents, and I don't think full automation is desirable. Indeed, having some control on where the anchor points are is necessary, and moreover, automation is very likely to produce unwanted behaviour (I'm thinking for instance about the issue with AP in `align*` environment, see §"Problems with amsmath" in [knowledge's documentation](https://texlive.mycozy.space/macros/latex/contrib/knowledge/knowledge.pdf)).
